#!/usr/bin/env python

import os
from collections import defaultdict
import numpy
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot

WIDTH = 7
HEIGHT = 6
BOTTOM = 0.4
LEFT = 0.7
MARGIN = 0.2

DIR = 'plot'
PCT = 10
COL = {
    'sort': '#0000ff',
    'heap': '#008000',
    'tree': '#ff0000',
    'move': '#000000',
}

class Comparison:
    def __init__(self, key):
        self.key = key
        self.r = defaultdict(list)
        self.seen_alg = set()
        self.seen_h = set()

    def add(self, alg, version, h, b, seed, time):
        if b == 1:
            return
        self.seen_alg.add(alg)
        self.seen_h.add(h)
        self.r[(alg, h)].append(time)

    def summarise(self):
        print self.key
        algs = list(sorted(self.seen_alg))
        hs = list(sorted(self.seen_h))

        SPP = matplotlib.figure.SubplotParams(
            left=LEFT/WIDTH, right=1.0 - MARGIN/WIDTH,
            bottom=BOTTOM/HEIGHT, top=1.0 - MARGIN/HEIGHT,
        )

        fig = matplotlib.pyplot.figure(figsize=(WIDTH, HEIGHT), subplotpars=SPP)
        ax = fig.add_subplot(111)
        ax.set_xscale('log')

        maxt = 0
        for alg in algs:
            t = []
            ta = []
            tb = []
            for h in hs:
                k = (alg, h)
                r = self.r[k]
                t.append(numpy.median(r))
                ta.append(numpy.percentile(r, PCT))
                tb.append(numpy.percentile(r, 100-PCT))
            ax.plot(hs, t,
                color=COL[alg],
                marker='o',
                mec=COL[alg],
                mfc='#ffffff',
                ms=5,
            )
            ax.fill_between(hs, ta, tb,
                facecolor=COL[alg],
                alpha=0.05,
            )
            if alg != 'move':
                maxt = max(maxt, max(t))

        ax.set_xlim((min(hs)/2., max(hs)*2.))
        ax.set_ylim((0, 1.2 * maxt))
        fig.savefig('{}/summary-{}.pdf'.format(DIR, self.key))
        matplotlib.pyplot.close(fig)


class Analysis:
    def __init__(self):
        self.comp = {}

    def read(self, filename):
        with open('result/{}'.format(filename)) as f:
            for l in f:
                alg, h, b, gen, seed, time = l.rstrip('\n').split('\t')
                h = int(h)
                b = int(b)
                size = h * b
                seed = int(seed)
                time = float(time)
                keys = []
                keys.append('{}'.format(size))
                keys.append('{}-{}'.format(size, gen))
                for key in keys:
                    if key not in self.comp:
                        self.comp[key] = Comparison(key)
                    self.comp[key].add(alg, filename, h, b, seed, time)

    def summarise(self):
        for key in sorted(self.comp.keys()):
            self.comp[key].summarise()

def main():
    if not os.path.exists(DIR):
        os.makedirs(DIR)
    r = Analysis()
    r.read('gcc-short')
    r.read('gcc-long')
    r.summarise()

main()
