#!/bin/sh

if [ "$1" = "" ]; then
    seed="1"
else
    seed="$1"
fi

batch/test-cases 7 | while read h b; do
    for version in gcc-short gcc-long; do
        for alg in 0 1; do
            for gen in 0 1; do
                sbatch batch/test-batch "$version" "$h" "$b" "$alg" "$gen" 0
            done
            for gen in 2 3 4 5 6; do
                sbatch batch/test-batch "$version" "$h" "$b" "$alg" "$gen" "$seed"
            done
        done
    done
done

