Import('env')
common = [
    'DataGenerator.cc', 'TestDriver.cc', 'MedianAlgorithm.cc',
    'SortMedian.cc', 'HeapMedian.cc', 'TreeMedian.cc', 'MoveMedian.cc',
    'Util.cc'
]
env.Program('tester', ['tester.cc'] + common)
env.Program('verify', ['verify.cc'] + common)
