name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bin/build-gcc
    - name: Test (short)
      run: build-gcc-short/verify
    - name: Test (long)
      run: build-gcc-long/verify
